services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    container_name: phonebooks.api
    build:
      context: .
      dockerfile: Solomonlol.Phonebook/Dockerfile

  phonebook.database:
      image: postgres:latest
      container_name: phonebooks.database
      environment:
        - POSTGRES_DB=PhonebookDB
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      # volumes:
      #   - ./.containers/phonebooks-db:/var/lib/postgresql/data
      ports:
      - 5432:5432
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d PhonebookDB"]
        interval: 5s
        timeout: 5s
        retries: 10