services:
  frontend:
    image: solomonlol/phonebook-compose:1.0
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    depends_on:
      phonebook.database:
        condition: service_healthy
    stdin_open: true
    tty: true
    environment:
      ConnectionStrings__PostgresConnection: "Host=phonebook.database;Port=5432;Username=postgres;Password=postgres;Database=PhonebookDB"
      DataProtection__KeysPath: /keys
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - phonebook-keys:/keys

  phonebook.database:
      image: postgres:17-alpine
      container_name: phonebooks.database
      environment:
        - POSTGRES_DB=PhonebookDB
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - phonebook-db:/var/lib/postgresql/data
      ports:
      - 5432:5432
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d PhonebookDB"]
        interval: 5s
        timeout: 5s
        retries: 10

volumes:
  phonebook-db:
  phonebook-keys:
